title: Made With Abandon
author: madewithabandon
email: marissabriesmith@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learn about Marissa Smith - hobbies, interestes, and experiences

# social links
twitter_username: MarissaBrie # DO NOT include the @ character, or else the build will fail!
github_username:  madewithabandon # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
